name: Sync2NAS
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - anaconda
  - pip
  - configparser
  - coverage
  - paramiko
  - pip:
    - tmdbsimple
    - rich-click
    - pytest-mock
    - pytest-cov
    - uv
    - pymilvus
    - psycopg2
    - fastapi>=0.104.0
    - uvicorn[standard]>=0.24.0
    - pydantic>=2.5.0
    - python-multipart>=0.0.6
    - openai>=1.93.0
    - ollama=0.5.1
    - anthropic==0.56.0
    - ttkbootstrap==1.14.2
